### ISSUE TITLE
Binder.bind(PropertyAdapter source).to(HasValue<?> widget)

### ISSUE THREAD

**Issue by anton-johansson** [ltearno/hexa.tools#3]
Hey!

I've been messing around a bit with GWT and Hexa Binding. I noticed one thing. If you have a model that already has data in it and you bind it to a Widget (HasValue<?>), the Widget won't take the models current value.

Maybe it's not always what you want, but in my case I'd like it.

In my case, I have a simple HashMap as my model. I create a one-way property adapter for it (implementing PropertyAdapter). This of course means that if I make changes to my Map, it won't be reflected to the bound component, but that is fine.

The Map has default values set on them, and when I bind each key to a GWT component, I want that GWT component to immediately get the models value.

Can we work this out, you think? Maybe a new overload, `to(HasValue<?> widget, boolean useExistingModelValue);`

**Comment by ltearno** [comment]
Hi Anton,

Normally the first thing a data binding does is to propagate the value from
the source to the destination. So you should not have to call nothing to
geth that done.

This means there might be a problem else where.

I suggest two things :
- when you create the data binding, add a call to the
  **log("myBindingLittleName")** method. You should at least see a message saying
  "propagating to destination". Is it the case ?
- could you please provide me with a minimum code snippet to reproduce the
  problem ?

Thanks a lot !

Arnaud

Le mar. 30 juin 2015 à 14:48, Anton Johansson notifications@github.com a
écrit :

**Comment by anton-johansson** [comment]
A one-way binding does that yes, but I thought there was support for two-way binding. I.e. if the model is updated, the GUI is updated and if the GUI is updated, the model is updated.

Let me try the .log(String) method and I'll get back to you (with a code snippet too)!

**Comment by ltearno** [comment]
Hi Anton,

Do you have any update on your problem ?

Please, maybe you could send few lines of code showing what does not work as expected ?

Thanks

**Comment by BenDol** [comment]
So if the model has data in it before it is bound to the object it should map that data directly to its partner bind? This should already be the case from what I have tested.

``` java
    Binder.bind(this.setting, "type").to(typeListBox);
```

This works fine for me, I would suggest you have a problem with your custom PropertyAdapter, when it calls getValue or setValue perhaps.

**Comment by anton-johansson** [comment]
My GWT project is currently on hold so I haven't been working on this. However, my guess is that @BenDol is correct here.

Closing for now!
